# -*- coding: utf-8 -*-
"""Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug4EdRF7u784h9fBINzk-bT71QBYAjb9
"""

# Install Libraries
!pip install pandas numpy scikit-learn streamlit pyngrok plotly
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.ensemble import RandomForestRegressor

# Upload Dataset
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("Advertising.csv")
df.head()

# Feature Selection
X = df[['TV','Radio','Newspaper']]
y = df['Sales']

# Train/Test Split
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train Model
model = RandomForestRegressor(
    n_estimators=500,
    random_state=42
)
model.fit(X_train,y_train)

# Model Evaluation
pred = model.predict(X_test)
print("R2 Score:", r2_score(y_test,pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test,pred)))

# Save Model
pickle.dump(model,open("sales_model.pkl","wb"))
pickle.dump(scaler,open("scaler.pkl","wb"))

# Commented out IPython magic to ensure Python compatibility.
# # Streamlit UI
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import pickle
# import plotly.express as px
# 
# # Load model
# model = pickle.load(open("sales_model.pkl","rb"))
# scaler = pickle.load(open("scaler.pkl","rb"))
# 
# st.set_page_config(
#     page_title="AI Sales Prediction Dashboard",
#     page_icon="📈",
#     layout="wide"
# )
# 
# # CSS Styling
# st.markdown("""
# <style>
# .title {
# font-size:70px;
# font-weight:800;
# text-align:center;
# color:#2E86C1;
# }
# .subtitle {
# text-align:center;
# font-size:22px;
# color:gray;
# margin-bottom:20px;
# }
# .metric-card {
# background-color:#F4F6F7;
# padding:20px;
# border-radius:12px;
# text-align:center;
# }
# </style>
# """, unsafe_allow_html=True)
# st.markdown('<p class="title">📈 AI Sales Prediction</p>', unsafe_allow_html=True)
# st.markdown('<p class="subtitle">Predict product sales based on advertising spend</p>', unsafe_allow_html=True)
# st.divider()
# 
# # Sidebar Inputs
# st.sidebar.header("Advertising Budget")
# tv = st.sidebar.slider("TV Advertising Budget ($)",0,300,100)
# radio = st.sidebar.slider("Radio Advertising Budget ($)",0,50,25)
# news = st.sidebar.slider("Newspaper Advertising Budget ($)",0,120,20)
# 
# # Prediction
# input_data = np.array([[tv,radio,news]])
# input_scaled = scaler.transform(input_data)
# prediction = model.predict(input_scaled)
# st.subheader("📊 Predicted Sales")
# st.success(f"Estimated Sales: {prediction[0]:.2f} units")
# st.divider()
# 
# # Dataset Analytics
# st.subheader("Advertising Impact Analysis")
# df = pd.read_csv("Advertising.csv")
# fig = px.scatter(
#     df,
#     x="TV",
#     y="Sales",
#     size="Radio",
#     color="Sales",
#     title="TV Advertising vs Sales"
# )
# st.plotly_chart(fig,use_container_width=True)
# fig2 = px.scatter(
#     df,
#     x="Radio",
#     y="Sales",
#     color="Sales",
#     title="Radio Advertising vs Sales"
# )
# st.plotly_chart(fig2,use_container_width=True)
# st.divider()
# st.markdown("""
# ### 🤖 Model Information
# 
# Model Used: **Random Forest Regressor**
# 
# Features Used:
# - TV Advertising Budget
# - Radio Advertising Budget
# - Newspaper Advertising Budget
# 
# Purpose:
# Predict product sales based on advertising investment.
# """)

# Run Streamlit
from pyngrok import ngrok
import time
import os
ngrok.kill()
!streamlit run app.py --server.port 8501 --server.headless true &>/content/logs.txt &
time.sleep(5)
public_url = ngrok.connect(8501)
print("🌍 Open this URL:", public_url)